<?php
return array (
  'l_user' => 
  array (
    'fieldid' => '111',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'l_user',
    'name' => '称呼',
    'tips' => '',
    'css' => 'style=width:65%;',
    'minlength' => '1',
    'maxlength' => '40',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'游客\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '游客',
    'ispassword' => '0',
  ),
  'l_phone' => 
  array (
    'fieldid' => '112',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'l_phone',
    'name' => '电话',
    'tips' => '',
    'css' => 'style=width:65%',
    'minlength' => '1',
    'maxlength' => '15',
    'pattern' => '/^[0-9-]{6,13}$/',
    'errortips' => '电话号码格式不正确',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'l_words' => 
  array (
    'fieldid' => '113',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'l_words',
    'name' => '留言',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '250',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'75\',
  \'height\' => \'46\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '75',
    'height' => '46',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
  'l_yzm' => 
  array (
    'fieldid' => '114',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'l_yzm',
    'name' => '验证码',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'idcode',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
);
?>